In [3]:
import numpy as np
import pandas as pd

In [4]:
spine=pd.read_csv(r"C:\Users\athar\Downloads\archive (26)\Dataset_spine.csv")

In [5]:
spine.head()

pelvic incidence   pelvic tilt   lumbar lordosis angle   sacral slope  \
0         63.027817     22.552586               39.609117      40.475232   
1         39.056951     10.060991               25.015378      28.995960   
2         68.832021     22.218482               50.092194      46.613539   
3         69.297008     24.652878               44.311238      44.644130   
4         49.712859      9.652075               28.317406      40.060784   

    pelvic radius   grade of spondylolisthesis Class_att  
0       98.672917                    -0.254400  Abnormal  
1      114.405425                     4.564259  Abnormal  
2      105.985135                    -3.530317  Abnormal  
3      101.868495                    11.211523  Abnormal  
4      108.168725                     7.918501  Abnormal

In [6]:
spine.shape

(310, 7)

In [7]:
spine.isnull().sum()

pelvic incidence               0
 pelvic tilt                   0
 lumbar lordosis angle         0
 sacral slope                  0
 pelvic radius                 0
 grade of spondylolisthesis    0
Class_att                      0
dtype: int64

In [8]:
spine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   pelvic incidence             310 non-null    float64
 1    pelvic tilt                 310 non-null    float64
 2    lumbar lordosis angle       310 non-null    float64
 3    sacral slope                310 non-null    float64
 4    pelvic radius               310 non-null    float64
 5    grade of spondylolisthesis  310 non-null    float64
 6   Class_att                    310 non-null    object 
dtypes: float64(6), object(1)
memory usage: 17.1+ KB


In [9]:
spine.describe()

pelvic incidence   pelvic tilt   lumbar lordosis angle   sacral slope  \
count        310.000000    310.000000              310.000000     310.000000   
mean          60.496653     17.542822               51.930930      42.953831   
std           17.236520     10.008330               18.554064      13.423102   
min           26.147921     -6.554948               14.000000      13.366931   
25%           46.430294     10.667069               37.000000      33.347122   
50%           58.691038     16.357689               49.562398      42.404912   
75%           72.877696     22.120395               63.000000      52.695888   
max          129.834041     49.431864              125.742385     121.429566   

        pelvic radius   grade of spondylolisthesis  
count      310.000000                   310.000000  
mean       117.920655                    26.296694  
std         13.317377                    37.559027  
min         70.082575                   -11.058179  
25%        110.709196                     1.603727  
50%        118.268178                    11.767934  
75%        125.467674                    41.287352  
max        163.071041                   418.543082

In [10]:
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [11]:
#splitting the data into X and Y

In [12]:
X=spine.drop("Class_att",axis=1)

In [13]:
Y=spine["Class_att"]

In [14]:
print(X)

     pelvic incidence   pelvic tilt   lumbar lordosis angle   sacral slope  \
0           63.027817     22.552586               39.609117      40.475232   
1           39.056951     10.060991               25.015378      28.995960   
2           68.832021     22.218482               50.092194      46.613539   
3           69.297008     24.652878               44.311238      44.644130   
4           49.712859      9.652075               28.317406      40.060784   
..                ...           ...                     ...            ...   
305         47.903565     13.616688               36.000000      34.286877   
306         53.936748     20.721496               29.220534      33.215251   
307         61.446597     22.694968               46.170347      38.751628   
308         45.252792      8.693157               41.583126      36.559635   
309         33.841641      5.073991               36.641233      28.767649   

      pelvic radius   grade of spondylolisthesis  
0         98

In [15]:
print(Y)

0      Abnormal
1      Abnormal
2      Abnormal
3      Abnormal
4      Abnormal
         ...   
305      Normal
306      Normal
307      Normal
308      Normal
309      Normal
Name: Class_att, Length: 310, dtype: object


In [16]:
scaler=StandardScaler()

In [17]:
X=scaler.fit_transform(X)

In [18]:
print(X)

[[ 0.14708636  0.50136873 -0.6651769  -0.18495031 -1.4476468  -0.70805942]
 [-1.24586434 -0.74876898 -1.45300075 -1.0415207  -0.26438488 -0.57955637]
 [ 0.4843695   0.46793218 -0.09926175  0.2730833  -0.89768556 -0.79542095]
 ...
 [ 0.05520137  0.51561812 -0.31097748 -0.31356364  0.58289256 -0.77348834]
 [-0.88582307 -0.88565951 -0.55861259 -0.47712775  0.04702109 -0.69554822]
 [-1.54892681 -1.24785954 -0.82539423 -1.05855695  0.45311695 -0.70658867]]


In [19]:
le=LabelEncoder()

In [20]:
Y=le.fit_transform(Y) #0-Abnormal,Y-normal

In [21]:
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=4)

In [24]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(248, 6)
(248,)
(62, 6)
(62,)


In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
model=LogisticRegression()

In [27]:
model.fit(X,Y)

LogisticRegression()

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
X_train_predict=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_predict,Y_train)

In [30]:
print(training_data_accuracy)

0.8508064516129032


In [31]:
input_data = (63.0278175,22.55258597,39.60911701,40.47523153,98.67291675,-0.254399986)
#changing the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)
# reshape the numpy array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
# standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)
prediction = model.predict(std_data)
print(prediction)
if(prediction[0] == 0):
    print('The person is abnormal')
else:
    print('The person is normal')

[[ 0.14708636  0.50136873 -0.6651769  -0.18495031 -1.4476468  -0.70805942]]
[0]
The person is abnormal


C:\Users\athar\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [32]:
input_data = (89.01487529,26.07598143,69.02125897,62.93889386,111.4810746,6.061508401)
#changing the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)
# reshape the numpy array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
# standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)
prediction = model.predict(std_data)
print(prediction)
if(prediction[0] == 0):
    print('The person is abnormal')
else:
    print('The person is normal')

[[ 1.65719824  0.85398421  0.92259902  1.49126296 -0.48432901 -0.53962801]]
[1]
The person is normal


C:\Users\athar\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [33]:
import joblib

In [34]:
joblib.dump(model,"classifier.pkl")

['classifier.pkl']

In [36]:
import joblib
from sklearn.linear_model import LogisticRegression

# Example: train model
model = LogisticRegression()
model.fit(X_train, Y_train)

# Save model
joblib.dump(model, "classifier.pkl")


['classifier.pkl']